### ISSUE TITLE
Twiss parameters typo in the OWLightSource class

### ISSUE THREAD

**Issue by jureyherrera** [lucarebuffi/OASYS-SYNED#5]
There is a funny typo in the list of items in the OWLightSource(OWWidget) class:

https://github.com/oasys-kit/OASYS-SYNED/blob/e5ec47b7d0df128dcbb9e89d7e03c1f4abdd2671/orangecontrib/syned/widgets/gui/ow_light_source.py#L151

Cheers,
Juan

**Comment by lucarebuffi** [comment]
:D :D :D :D 

Thanks for catching it up!
